In [1]:
from pandas import read_csv 
import numpy as np
from sklearn.linear_model import LinearRegression
from matplotlib import pyplot
from pandas.plotting import scatter_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix
path = r"D:/GP/Cousres/ML/lecture1/Tasks/HW/Uni-ML00-Lec1-Practice/iris.csv"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = read_csv(path, names=names )

In [2]:
x = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [3]:
cls = SVC()
cls.fit(x_train,y_train)
y_pred = cls.predict(x_test)
print("The confusion matrix \n " ,confusion_matrix(y_test,y_pred))
print("The classification report \n ",classification_report(y_test,y_pred))

The confusion matrix 
  [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
The classification report 
                   precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.86      1.00      0.92         6

       accuracy                           0.97        30
      macro avg       0.95      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [4]:
sepal_length = input("Enter sepal-length : ")
sepal_width = input("Enter sepal-width : ")
petal_length = input("Enter petal-length : ")
petal_width = input("Enter petal-width : ")
test = cls.predict([[sepal_length,sepal_width,petal_length,petal_width]])
print("The predicted class is :", test[0])
print("**********point1 DONE**************")

Enter sepal-length : 5.5
Enter sepal-width : 2.6
Enter petal-length : 4.4
Enter petal-width : 1.2
The predicted class is : Iris-versicolor
**********point1 DONE**************


In [4]:
sep_len = dataset.iloc[:,0].values
sep_wid = dataset.iloc[:,1].values
pet_len =dataset.iloc[:,2].values
pet_wid =dataset.iloc[:,3].values
corr2 = np.corrcoef(sep_len,pet_len)
print("The correlation between sep_len & pet_ len is the highest : \n", corr2)
print("********finding sep-len using pet_len*********")

The correlation between sep_len & pet_ len is the highest : 
 [[1.         0.87175416]
 [0.87175416 1.        ]]
********finding sep-len using pet_len*********


In [5]:
x_train,x_test,y_train,y_test = train_test_split(pet_len,sep_len,test_size = 0.2,random_state = 1)
lin_gre = LinearRegression()
lin_gre.fit(x_train.reshape(-1, 1),y_train.reshape(-1, 1))

LinearRegression()

In [8]:
sepal_width = input("Enter sepal-width : ")
petal_length = float(input("Enter petal-length : "))
petal_width = input("Enter petal-width : ")
length = lin_gre.predict(np.array(petal_length).reshape(-1, 1))
test1 = cls.predict([[length[0,0],sepal_width,petal_length,petal_width]])
print("The predicted class : " ,test1[0],"\n The predicted sep_len :" ,length[0,0])
print("**********point2 DONE**************")

Enter sepal-width : 2.6
Enter petal-length : 4.
Enter petal-width : 1.2
The predicted class :  Iris-versicolor 
 The predicted sep_len : 5.916875798660784
**********point2 DONE**************


In [11]:
def predict(input_1, input_2, input_3, start, end):
    col_to_predict = dataset.values[:, end]
    predicted_col = dataset.values[:, start]
    col_to_predict_train, col_to_predict_test, predicted_col_train, predicted_col_test = train_test_split(col_to_predict, predicted_col, test_size=0.2, random_state=1)
    lin_gre.fit(col_to_predict_train.reshape(-1, 1),predicted_col_train.reshape(-1, 1))
    if start == 0:
        Value4 = lin_gre.predict(np.array(input_1).reshape(-1, 1))
        test1 = cls.predict([[Value4[0,0], input_1, input_2, input_3]])
    elif start == 1:    
        Value4 = lin_gre.predict(np.array(input_1).reshape(-1, 1))
        test1 = cls.predict([[input_1,Value4[0,0],input_2,input_3]])
    elif start == 2:
        Value4 = lin_gre.predict(np.array(input_3).reshape(-1, 1))
        test1 = cls.predict([[input_1,input_2,Value4[0,0],input_3]])
    elif start == 3:
        Value4 = lin_gre.predict(np.array(input_3).reshape(-1, 1))
        test1 = cls.predict([[input_1,input_2,input_3,Value4[0,0]]])   
        
    print("The predicted class : " ,test1[0],"\n The predicted sep_len :" ,Value4[0,0])  
    
    
while True:
    my_input = input(
        'Enter 1. if sep_len is missing\nEnter 2. if sep_wid is missing\n'
        'Enter 3. if pet_len is missing\nEnter 4. if pet_wid is missing\n'
        'Enter 0. to exit\n')    
    if my_input == '0':
        break
    elif my_input == '1':
        sep_wid = float(input("Enter sep_wid : "))
        pet_len = input("Enter pet_len : ")
        pet_wid = input("Enter pet_wid : ")
        predict(sep_wid, pet_len, pet_wid, 0, 1)
    elif my_input == '2':
        sep_len =  float(input("Enter sep_len : "))
        pet_len =  input("Enter pet_len : ")
        pet_wid =  input("Enter pet_wid : ")
        predict(sep_len, pet_len, pet_wid, 1, 0)
    elif my_input == '3':
        sep_len =  input("Enter sep_len : ")
        sep_wid =  input("Enter sep_wid : ")
        pet_wid =  float(input("Enter pet_wid : "))
        predict(sep_len, sep_wid, pet_wid, 2, 3)
    elif my_input == '4':
        sep_len =  input("Enter sep_len : ")
        sep_wid =  input("Enter sep_wid : ")
        pet_len =  float(input("Enter pet_len : "))
        predict(sep_len, sep_wid, pet_len, 3, 2)    
    else:
        print('Invalid input!!!!!!!!!!!!!!!')
     

Enter 1. if sep_len is missing
Enter 2. if sep_wid is missing
Enter 3. if pet_len is missing
Enter 4. if pet_wid is missing
Enter 0. to exit
4
Enter sep_len : 5.1
Enter sep_wid : 3.5
Enter pet_len : 1.4
The predicted class :  Iris-setosa 
 The predicted sep_len : 0.19922370674169565
Enter 1. if sep_len is missing
Enter 2. if sep_wid is missing
Enter 3. if pet_len is missing
Enter 4. if pet_wid is missing
Enter 0. to exit
3
Enter sep_len : 5.1
Enter sep_wid : 3.5
Enter pet_wid : 0.2
The predicted class :  Iris-setosa 
 The predicted sep_len : 1.5794543030291814
Enter 1. if sep_len is missing
Enter 2. if sep_wid is missing
Enter 3. if pet_len is missing
Enter 4. if pet_wid is missing
Enter 0. to exit
2
Enter sep_len : 5.1
Enter pet_len : 1.4
Enter pet_wid : 0.2
The predicted class :  Iris-setosa 
 The predicted sep_len : 3.0590994098662607
Enter 1. if sep_len is missing
Enter 2. if sep_wid is missing
Enter 3. if pet_len is missing
Enter 4. if pet_wid is missing
Enter 0. to exit
1
Enter s