In [130]:
from pandas import read_csv 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.feature_selection import SelectKBest,chi2

In [131]:
path = r"D:/GP/Cousres/ML/lecture5/task/Uni-ML00-Lec5-Practice/Uni-ML00-Lec5-Practice/iris.csv"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = read_csv(path, names=names )

In [132]:
x = dataset.iloc[:,0:2].values
x1 = dataset.iloc[:,2:4].values
y = dataset.iloc[:,4].values

In [133]:
pca= PCA(n_components=1)
f= pca.fit(x)
print(f.components_)
x2 = pca.fit_transform(x)
print(x2)

[[ 0.99693955 -0.07817635]]
[[-0.77592505]
 [-0.93622478]
 [-1.15124796]
 [-1.24312428]
 [-0.88343664]
 [-0.50811373]
 [-1.26657719]
 [-0.86780137]
 [-1.42687692]
 [-0.94404242]
 [-0.49247846]
 [-1.06718928]
 [-1.03591874]
 [-1.53438851]
 [-0.11715554]
 [-0.24812004]
 [-0.50811373]
 [-0.77592505]
 [-0.20121423]
 [-0.79937796]
 [-0.46902555]
 [-0.79156032]
 [-1.28221246]
 [-0.76028978]
 [-1.06718928]
 [-0.83653083]
 [-0.86780137]
 [-0.67623109]
 [-0.66841346]
 [-1.15124796]
 [-1.04373637]
 [-0.46902555]
 [-0.72313691]
 [-0.43187268]
 [-0.94404242]
 [-0.8521661 ]
 [-0.37714923]
 [-0.94404242]
 [-1.43469455]
 [-0.76810741]
 [-0.875619  ]
 [-1.28027715]
 [-1.45032983]
 [-0.875619  ]
 [-0.79937796]
 [-1.03591874]
 [-0.79937796]
 [-1.25094192]
 [-0.59217241]
 [-0.85998373]
 [ 1.14171299]
 [ 0.54354927]
 [ 1.04983667]
 [-0.28333761]
 [ 0.67451376]
 [-0.12303787]
 [ 0.43603768]
 [-0.88931897]
 [ 0.76639008]
 [-0.61369001]
 [-0.75835447]
 [ 0.06071476]
 [ 0.2229498 ]
 [ 0.26792031]
 [-0.2305494

In [134]:
pca= PCA(n_components=1)
f= pca.fit(x1)
print(f.components_)
x3 = pca.fit_transform(x1)
print(x3)

[[0.92154695 0.38826694]]
[[-2.56137133e+00]
 [-2.56137133e+00]
 [-2.65352602e+00]
 [-2.46921663e+00]
 [-2.56137133e+00]
 [-2.20725385e+00]
 [-2.52254463e+00]
 [-2.46921663e+00]
 [-2.56137133e+00]
 [-2.50804333e+00]
 [-2.46921663e+00]
 [-2.37706194e+00]
 [-2.60019802e+00]
 [-2.87666211e+00]
 [-2.74568072e+00]
 [-2.39156324e+00]
 [-2.57587263e+00]
 [-2.52254463e+00]
 [-2.24608055e+00]
 [-2.43038994e+00]
 [-2.28490724e+00]
 [-2.39156324e+00]
 [-2.92999011e+00]
 [-2.16842716e+00]
 [-2.10059785e+00]
 [-2.37706194e+00]
 [-2.29940855e+00]
 [-2.46921663e+00]
 [-2.56137133e+00]
 [-2.37706194e+00]
 [-2.37706194e+00]
 [-2.39156324e+00]
 [-2.50804333e+00]
 [-2.56137133e+00]
 [-2.50804333e+00]
 [-2.74568072e+00]
 [-2.65352602e+00]
 [-2.50804333e+00]
 [-2.65352602e+00]
 [-2.46921663e+00]
 [-2.61469933e+00]
 [-2.61469933e+00]
 [-2.65352602e+00]
 [-2.22175516e+00]
 [-2.02294446e+00]
 [-2.52254463e+00]
 [-2.37706194e+00]
 [-2.56137133e+00]
 [-2.46921663e+00]
 [-2.56137133e+00]
 [ 9.45653940e-01]
 [ 8.

In [137]:
arr1 = np.column_stack((x2,x3,y))
np.savetxt('iris4.csv',arr1,delimiter= ',',fmt =' %f,%f,%s')
print("File Saved")
#print(arr1)

File Saved


In [138]:
path = r"D:/GP/Cousres/ML/lecture5/task/HW/MySolution/iris4.csv"
names = ['sepal', 'petal', 'class']
dataset = read_csv(path, names=names )

In [139]:
x = dataset.iloc[:,[0,1]].values
y = dataset.iloc[:,2].values
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [140]:
cls = SVC()
cls.fit(x_train,y_train)
y_pred = cls.predict(x_test)
print("The confusion matrix \n " ,confusion_matrix(y_test,y_pred))
print("The classification report \n ",classification_report(y_test,y_pred))

The confusion matrix 
  [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
The classification report 
                   precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.86      1.00      0.92         6

       accuracy                           0.97        30
      macro avg       0.95      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [141]:
sepal = input("Enter sepal  : ")
petal = input("Enter petal  : ")
test = cls.predict([[sepal,petal]])
print("The predicted class is :", test[0])

Enter sepal  : -1.1
Enter petal  : -2.3
The predicted class is : Iris-setosa


In [143]:
path = r"D:/GP/Cousres/ML/lecture5/task/Uni-ML00-Lec5-Practice/Uni-ML00-Lec5-Practice/Sport4.csv"
names = ['height', 'weight', 'age','class']
dataset = read_csv(path, names = names)

In [144]:
x = dataset.iloc[:,0:3].values
y = dataset.iloc[:,3].values
chi = SelectKBest(score_func=chi2,k=2)
f = chi.fit(x,y)  
print(f.scores_)## selected weight & age
x2= f.transform(x)
print(x2)

[ 387.78163747 3026.03532426  390.48966852]
[[ 75  26]
 [ 91  35]
 [ 95  36]
 ...
 [121  15]
 [125  26]
 [103  24]]


In [146]:
arr1 = np.column_stack((x2,y))
np.savetxt('Sport1.csv',arr1,delimiter= ',',fmt =' %f,%f,%s')
print("File Saved")
print(arr1)

File Saved
[[75 26 'basket']
 [91 35 'basket']
 [95 36 'basket']
 ...
 [121 15 'sumo']
 [125 26 'sumo']
 [103 24 'sumo']]
