In [5]:
from pandas import read_csv 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.feature_selection import SelectKBest,chi2

In [6]:
path = r"D:/GP/Cousres/ML/lecture6/tasks/Uni-ML00-Lec6-Practice/iris_Missing.csv"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = read_csv(path, names=names )
print(dataset)

     sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             NaN          3.1           1.5          NaN     Iris-setosa
4             NaN          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [15]:
NANCols = list(dataset.columns[dataset.isna().any()])
for col in NANCols:
    MeanValue = dataset[col].mean()
    dataset[col].fillna(MeanValue, inplace=True)
print(dataset)

     sepal-length  sepal-width  petal-length  petal-width           class
0        5.100000          3.5           1.4     0.200000     Iris-setosa
1        4.900000          3.0           1.4     0.200000     Iris-setosa
2        4.700000          3.2           1.3     0.200000     Iris-setosa
3        5.870345          3.1           1.5     1.187324     Iris-setosa
4        5.870345          3.6           1.4     0.200000     Iris-setosa
..            ...          ...           ...          ...             ...
145      6.700000          3.0           5.2     2.300000  Iris-virginica
146      6.300000          2.5           5.0     1.900000  Iris-virginica
147      6.500000          3.0           5.2     2.000000  Iris-virginica
148      6.200000          3.4           5.4     2.300000  Iris-virginica
149      5.900000          3.0           5.1     1.800000  Iris-virginica

[150 rows x 5 columns]


In [16]:
x = dataset.iloc[:,0:2].values
x1 = dataset.iloc[:,2:4].values
y = dataset.iloc[:,4].values

In [17]:
pca= PCA(n_components=1)
f= pca.fit(x)
print(f.components_)
x2 = pca.fit_transform(x)
print(x2)

[[ 0.99886744 -0.04757981]]
[[-0.79066999]
 [-0.96665357]
 [-1.17594302]
 [-0.0021657 ]
 [-0.02595561]
 [-0.51004169]
 [-1.28534573]
 [-0.88579876]
 [-1.46132931]
 [-0.97141156]
 [-0.50052572]
 [-1.08557224]
 [-1.06654032]
 [-1.56597404]
 [-0.07026516]
 [-0.23417136]
 [-0.51004169]
 [-0.79066999]
 [-0.20562347]
 [-0.80494394]
 [-0.48625178]
 [-0.80018596]
 [-1.29486169]
 [-0.78115403]
 [-1.08557224]
 [-0.86676683]
 [-0.88579876]
 [-0.69078325]
 [-0.68602527]
 [-1.17594302]
 [-1.0712983 ]
 [-0.01643965]
 [-0.04974552]
 [-0.42442889]
 [-0.97141156]
 [-0.87628279]
 [-0.39112302]
 [-0.97141156]
 [-1.46608729]
 [-0.78591201]
 [-0.86935911]
 [-1.33289468]
 [-1.47560326]
 [-0.89055674]
 [-0.03547157]
 [-1.06654032]
 [-0.80494394]
 [-1.27582977]
 [-0.60041247]
 [-0.88104077]
 [ 1.12145209]
 [ 0.52213162]
 [ 1.02632332]
 [-0.33402724]
 [ 0.64105029]
 [-0.15804366]
 [ 0.4174869 ]
 [-0.93810569]
 [ 0.73617905]
 [-0.6527194 ]
 [-0.81918702]
 [ 0.03221387]
 [ 0.12950833]
 [ 0.23674533]
 [-0.2626883

In [18]:
pca= PCA(n_components=1)
f= pca.fit(x1)
print(f.components_)
x3 = pca.fit_transform(x1)
print(x3)

[[0.92750254 0.37381685]]
[[-2.52584832]
 [-2.52584832]
 [-2.61859857]
 [-2.06401973]
 [-2.52584832]
 [-2.17283419]
 [-2.48846663]
 [-0.36907833]
 [-2.52584832]
 [-2.47047975]
 [-2.43309807]
 [-2.34034781]
 [-2.56323   ]
 [-2.84148077]
 [-2.71134883]
 [-2.35833469]
 [-2.5438352 ]
 [-2.48846663]
 [-0.33169665]
 [-2.39571638]
 [-2.24759756]
 [-2.35833469]
 [-2.89684933]
 [-2.1354525 ]
 [-2.06209705]
 [-2.34034781]
 [-2.26558444]
 [-2.43309807]
 [-2.52584832]
 [-2.34034781]
 [-2.34034781]
 [-2.35833469]
 [-2.47047975]
 [-2.52584832]
 [-2.47047975]
 [-2.71134883]
 [-2.61859857]
 [-2.47047975]
 [-2.61859857]
 [-2.43309807]
 [-2.24952024]
 [-2.58121689]
 [-2.61859857]
 [-2.19082107]
 [-1.98733368]
 [-2.48846663]
 [-2.34034781]
 [-2.52584832]
 [-2.43309807]
 [-2.52584832]
 [ 0.98349028]
 [ 0.83537146]
 [ 1.20637248]
 [ 0.29685682]
 [ 0.92812172]
 [ 0.76060809]
 [ 1.05825366]
 [-0.46454001]
 [ 0.85335834]
 [ 0.24148825]
 [-0.2790395 ]
 [ 0.44023712]
 [ 0.18471177]
 [ 0.98349028]
 [-0.07414419]

In [20]:
arr1 = np.column_stack((x2,x3,y))
np.savetxt('Missung_iris2.csv',arr1,delimiter= ',',fmt =' %f,%f,%s')
print("File Saved")
print(arr1)

File Saved
[[-0.790669992594029 -2.525848318874247 'Iris-setosa']
 [-0.9666535736988259 -2.525848318874245 'Iris-setosa']
 [-1.1759430242681375 -2.6185985727379792 'Iris-setosa']
 [-0.0021657018568057083 -2.0640197338690265 'Iris-setosa']
 [-0.02595560861717156 -2.5258483188742447 'Iris-setosa']
 [-0.5100416862045715 -2.172834186352811 'Iris-setosa']
 [-1.2853457309048668 -2.4884666334091303 'Iris-setosa']
 [-0.8857987551745361 -0.3690783311414828 'Iris-setosa']
 [-1.4613293120096655 -2.5258483188742447 'Iris-setosa']
 [-0.9714115550508989 -2.4704797504756244 'Iris-setosa']
 [-0.5005257235004251 -2.4330980650105096 'Iris-setosa']
 [-1.0855722430397017 -2.3403478111467755 'Iris-setosa']
 [-1.066540317631409 -2.5632300043393594 'Iris-setosa']
 [-1.565974037294322 -2.8414807659305636 'Iris-setosa']
 [-0.07026515780085048 -2.711348826601714 'Iris-setosa']
 [-0.23417136116718965 -2.3583346940802805 'Iris-setosa']
 [-0.5100416862045715 -2.54383520180775 'Iris-setosa']
 [-0.790669992594027 -2

In [21]:
path = r"D:/GP/Cousres/ML/lecture6/tasks/HW/MySolution/Missung_iris2.csv"
names = ['sepal', 'petal', 'class']
dataset = read_csv(path, names=names )

In [22]:
x = dataset.iloc[:,[0,1]].values
y = dataset.iloc[:,2].values
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [23]:
cls = SVC()
cls.fit(x_train,y_train)
y_pred = cls.predict(x_test)
print("The confusion matrix \n " ,confusion_matrix(y_test,y_pred))
print("The classification report \n ",classification_report(y_test,y_pred))

The confusion matrix 
  [[11  0  0]
 [ 0 12  1]
 [ 0  1  5]]
The classification report 
                   precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.92      0.92      0.92        13
 Iris-virginica       0.83      0.83      0.83         6

       accuracy                           0.93        30
      macro avg       0.92      0.92      0.92        30
   weighted avg       0.93      0.93      0.93        30



In [25]:
sepal = input("Enter sepal  : ")
petal = input("Enter petal  : ")
test = cls.predict([[sepal,petal]])
print("The predicted class is :", test[0])

Enter sepal  : -0.8
Enter petal  : -2.2
The predicted class is : Iris-setosa
